### PR TITLE
Remove Comments and PreProcessorDirective also for Enums.

### PR DESCRIPTION
**Pull request by BlueBasher**
- Found that comments and PreProcessorDirective only were removed for classes. So added the same logic into the Enum-file lines loop.
- Fixed a bug that when the Working Directory did not exists, the newly created dir was assigned to LocalConvertDir instead of LocalWorkingDir.
- Separated the Converting logic and the MSBuildTask by moving the code to a ConvertService.
- Added a MTTRunner ConsoleApp to help in quickly running/debugging the ConvertService.

Not sure if you like the last 2 items. If not, let me know and I'll change the code into only the 2 fixes.

### CODE REVIEW

**Comment by CodySchrank** [comment]
I have no problem with the last two as long as they do not affect the way MTT runs.  

I don't have much free time right now but I'll try to take a look at this soon!

**Comment by CodySchrank** [comment]
I don't use VS so I'm not sure how you start the MTTRunner with the example project.  I'll merge it all though given that you fixed a couple bugs and MTT core functionality hasn't changed.

**Comment by CodySchrank** [comment]
@BlueBasher Can you give me an example of how to use the MTTRunner?

**Comment by BlueBasher** [comment]
@CodySchrank The MTTRunner requires 2 arguments, the Convert directory and the Working directory. So you should be able to start it using MTTRunner.exe c:\tmp\csharp c:\tmp\typescript

I wasn't aware you don't use VS. To build the runner you would need VS Community.
Shall I change the MTTRunner so it is a .NET Core ConsoleApp?

**Comment by BlueBasher** [comment]
@CodySchrank I converted (#24) the MTTRunner into a .NET Core app so it's more easy to use.

You can then simply run it using `dotnet run c:\tmp\typescript c:\tmp\csharp`

**Comment by CodySchrank** [comment]
@BlueBasher Ah I should I have been clear, I understand how it runs just not in VS ;)

Anyways, thank you for converting it to a .NET Core App, I haven't used VS in like 5 years.

**Pull request merged**
